feat: implement minimal server
VoiceDeck/app pull request #10
Opened 2024-01-20 01:01 UTC by baumstern

This PR implements a basic version of the model and controller.

To retrieve all minted impact reports, the following method can be used:

```
export const loader = async (): Promise<IReportLoader> => {
    const reportService = await ReportService.getInstance();
    const reports = reportService.reports;
    return { reports };
};
```

Currently, all minted hypercert claims and metadata are retrieved when `ReportService` is first instantiated.

Future Work:

* Properly define `Report` model
* Implement server-side updates for newly added reports

2024-01-21 10:12 UTC, thebeyondr requested changes
hey, please use functional programming tools over object-oriented ones. look into using functions, types and hooks instead of creating classes, models and controllers.

2024-01-22 06:46 UTC, thebeyondr commented on app/routes/hypercert-reports.server..tsx
@baumstern waddup so I remade the connector in a functional way since I randomly woke up at midnight🤷🏽‍♂️. Feel free to edit as you please. I haven't removed any of your code so feel free to update that as needed. thanks for laying the foundation.
@CJ-Rose please give this a gander as well.

The idea is that this acts as a resource route in Remix. Other UI routes can call `/hypercert-reports` and get data back

- [ ] Re-add daehyuns hypercert documentation comments for gql
- [ ] Setup UI to get data and cache it in session
- [ ] IPFS speed check, it was slow even for hypercert docs (so is it viable to retrieve report data from it? hmmmm)
- [ ] go back to sleep

2024-01-22 15:10 UTC, baumstern commented on app/routes/hypercert-reports.server..tsx
thanks for jumping in with the code! quick question: How's the caching handled with the functional approach? Used a singleton in my version to cut down on Graph/IPFS requests

2024-01-22 15:20 UTC, baumstern commented
> hey, please use functional programming tools over object-oriented ones. look into using functions, types and hooks instead of creating classes, models and controllers.

main focus here was just nailing the functionality. But exploring functional programming now seems like a cool idea too -- I gotta say good bye to old school ways

2024-01-22 16:30 UTC, thebeyondr commented on app/routes/hypercert-reports.server..tsx
caching isn't handled rn, thats the responsibility of the client. This is just responsible for returning that data. 

Re: limiting requests, I'm sure there was still a loop fetching the metadata for each claim so it wasn't like a batched thing.

2024-01-22 16:35 UTC, thebeyondr commented
> main focus here was just nailing the functionality. But exploring functional programming now seems like a cool idea too -- I gotta say good bye to old school ways

np, I just find functional programming ends up less buggy and verbose

2024-01-22 20:37 UTC, baumstern commented on app/routes/hypercert-reports.server..tsx
> caching isn't handled rn, thats the responsibility of the client. This is just responsible for returning that data.
> 
> Re: limiting requests, I'm sure there was still a loop fetching the metadata for each claim so it wasn't like a batched thing. How does a singleton help us batch requests? Also, can you point me to the singleton implementation?

server-side caching decouples the client from external services (such as Graph and IPFS), reducing redundant calls to these services. It retrieves and stores data upon instantiation.

It had implemented using `static` keyword:
* https://github.com/VoiceDeck/app/pull/10/commits/dc5e64161ccb62d8d4f42577f9c880c987e1586c#diff-3d7ef1b624b061d38b0608ad49c35092d267df101e1122eacfc44fc77b3339ceR8
* https://github.com/VoiceDeck/app/pull/10/commits/dc5e64161ccb62d8d4f42577f9c880c987e1586c#diff-3d7ef1b624b061d38b0608ad49c35092d267df101e1122eacfc44fc77b3339ceR21

2024-01-22 20:41 UTC, baumstern commented on app/routes/hypercert-reports.server..tsx
Actually, I've scrapped the class implementation and replaced it with a module-scope variable, as it preserves data until the server process terminates. It's neater – thanks for the suggestion

2024-01-22 21:01 UTC, thebeyondr commented on app/routes/hypercert-reports.server..tsx
> server-side caching decouples the client from external services (such as Graph and IPFS), reducing redundant calls to these services. It retrieves and stores data upon instantiation.

hmm, a few things:
1) How do we allow the server cache to expire or tell it to fetch new data? 
2) I don't think this subverts the need for client-side caching. we need them both - what do you think?
3) What type of test would allow us to verify that your implementation actually caches?

2024-01-22 21:40 UTC, baumstern commented on app/routes/hypercert-reports.server..tsx
> > server-side caching decouples the client from external services (such as Graph and IPFS), reducing redundant calls to these services. It retrieves and stores data upon instantiation.
> 
> hmm, a few things:
> 
>     1. How do we allow the server cache to expire or tell it to fetch new data?
> 
>     2. I don't think this subverts the need for client-side caching. we need them both - what do you think?
> 
>     3. What type of test would allow us to verify that your implementation actually caches?

1. the server should be notified when a Hypercert is minted, so it can update the entry
2. sure, they serve different purposes
3. I will add a test case

2024-01-22 22:22 UTC, thebeyondr commented on app/routes/hypercert-reports.server..tsx
awesome, thanks for your efforts so far. we're closer now 🫡

2024-01-23 03:27 UTC, thebeyondr commented on app/routes/hypercert-reports.server..tsx
I can't believe this was posted today, as we're talking about cache. 💥

https://youtu.be/RXMvnqb7A8k

2024-01-23 04:44 UTC, baumstern commented on app/routes/hypercert-reports.server..tsx
> I can't believe this was posted today, as we're talking about cache. 💥
> 
> https://youtu.be/RXMvnqb7A8k

Is he Big Brother? 🤔🤔

2024-01-23 04:45 UTC, baumstern commented
@thebeyondr added tests, please take another look!

2024-01-26 15:52 UTC, thebeyondr requested changes
just a few small things then we're good!

2024-01-26 15:52 UTC, thebeyondr commented on package.json
>      "lint": "biome check --apply ./app",
can we remove this?

2024-01-26 15:52 UTC, thebeyondr commented on package.json
>      "@remix-run/dev": "^2.5.0",
can we remove this?

2024-01-26 15:52 UTC, thebeyondr commented on docs/server.md
> +# Server Design
why is this here and not in README?

2024-01-26 21:31 UTC, baumstern commented on package.json
>      "lint": "biome check --apply ./app",
Removed in 6373f32

2024-01-26 21:31 UTC, baumstern commented on package.json
>      "@remix-run/dev": "^2.5.0",
Removed in 6373f32

2024-01-26 21:31 UTC, baumstern commented on docs/server.md
> +# Server Design
Moved to README.md in 6373f32

2024-01-27 19:44 UTC, thebeyondr approved these changes
lfg

2024-01-27 19:44 UTC, merged