config/add font and colors to tailwind
VoiceDeck/app pull request #7
Opened 2024-01-14 19:51 UTC by CJ-Rose

2024-01-15 05:06 UTC, thebeyondr commented on tailwind.config.js
> +        textBlue: "#252F56",
I think we should name our custom tokens with a prefix (eg. `vd-*`) to distinguish them. We should also maintain the tailwind kebab-case for consistency.

Examples:

- `vd-text-blue`
- `vd-beige-400`

What do you think?

2024-01-15 05:13 UTC, thebeyondr commented on app/root.tsx
> +            href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200..700&display=swap"
The most ideal option for us at PSE is usually to self-host the fonts. (download them and add them to our repo). 

However, we tend to use [Fontsource](https://fontsource.org/) or [Bunny Fonts](https://fonts.bunny.net/) if we're going to go the CDN route as they respect privacy more than Google! (or so they claim)

2024-01-16 02:23 UTC, thebeyondr requested changes
So I pulled this and the colors worked but the font didn't change. I'll leave this for you to find and fix. 

I'm confident it isn't a faulty config or conflict on my part so I think it just wasn't properly tested _before_ the review process. 

We aren't doing test-driven development but we still need to check that our implementations work for sure. happy hunting!

2024-01-16 02:36 UTC, CJ-Rose commented
> So I pulled this and the colors worked but the font didn't change

@thebeyondr did you try removing the remix default styling on the main div of `_index.tsx`? The inline style there overrides the font set in `tailwind.css.`
I debated about including changes to that file that were only for testing purposes, and ultimately decided to leave it out.

2024-01-16 02:53 UTC, thebeyondr commented
> @thebeyondr did you try removing the remix default styling on the main div of `_index.tsx`? 

I already knew that's what it was, but I'm encouraging you to fully complete your tasks as I'll be trusting you to make feature complete things in the future. 💪🏽

You don't have to include the tests, remove the tests and keep the feature! However, if I'm asked to review a feature and there is no feature, I'll assume there was no test.

2024-01-16 14:17 UTC, thebeyondr approved these changes

2024-01-16 14:18 UTC, merged